spring.datasource.url=jdbc:mysql://localhost:3306/e_commerce
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#spring.main.allow-circular-references=true

spring.mail.host=smtp.gmail.com
spring.mail.username=prudhviandem1234@gmail.com
spring.mail.password=zzqirunvenjzxlwf
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.thymeleaf.cache=false

# Sale settings
sale.active=true
sale.discount=20  
sale.start=2024-02-21
sale.end=2024-03-07